version: "3"
services:
    www:
        build: .
        ports:
            - "8001:80"
        volumes:
            - .:/var/www/html/Frontend
            - /Users/mzadrazil001/Projects/Library:/var/www/html/Library
            - /Users/mzadrazil001/Projects/CMS:/var/www/html/CMS
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 318_cms
            MYSQL_ROOT_PASSWORD: somepass
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    adminer:
        image: adminer
        links:
            - db
        ports:
            - 8080:8080

volumes:
    persistent: